---
title: "Minimal stargazer type example for R Markdown"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r stargazerType, echo=FALSE}
if (!is.null(knitr::current_input())) {
  output_formats <- rmarkdown::all_output_formats(knitr::current_input())
  output_format <- if (length(output_formats) > 0) output_formats[1] else NULL

  if (!is.null(output_format) && output_format == "pdf_document") {
    stargazer_type <- "latex"
  } else if (!is.null(output_format) && output_format == "html_document") {
    stargazer_type <- "html"
  } else {
    stargazer_type <- "html"
  }
} else {
  stargazer_type <- "text"
}
```

This document chooses `stargazer_type` from the R Markdown output format.

```{r models}
library(stargazer)

model_1 <- lm(mpg ~ wt + hp, data = mtcars)
model_2 <- lm(mpg ~ wt + hp + am, data = mtcars)
```

```{r table, results='asis'}
stargazer(
  model_1,
  model_2,
  dep.var.labels = "Miles per gallon",
  covariate.labels = c("Weight", "Horsepower", "Manual transmission"),
  notes = paste0(
    "The same stargazer call can render as HTML, LaTeX, or text. ",
    "Only the value of type changes."),
  keep.stat = "n",
  notes.append = TRUE,
  digits = 2,
  type = stargazer_type
)
```
